# =====================================================================
# Crossplane Claim — XPostgreSQLInstance
# =====================================================================

apiVersion: database.poc.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: app-demo-db
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  parameters:
    dbName: app_demo
    owner: platform
    connectionLimit: 20