# =====================================================================
# Crossplane Composition
# =====================================================================

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpostgresqlinstance-database
  labels:
    provider: postgresql
spec:
  compositeTypeRef:
    apiVersion: database.poc.io/v1alpha1
    kind: XPostgreSQLInstance
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: database
            base:
              apiVersion: postgresql.postgresql.upbound.io/v1alpha1
              kind: Database
              spec:
                forProvider:
                  encoding: UTF8
                  template: template0
                providerConfigRef:
                  name: postgresql-config
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.dbName
                toFieldPath: spec.forProvider.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.owner
                toFieldPath: spec.forProvider.owner
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.connectionLimit
                toFieldPath: spec.forProvider.connectionLimit